### ISSUE TITLE
gcode parameter window size

### ISSUE THREAD

**Issue by swarfer** [OpenBuilds/cam#13]
Hiya
On my Elitebook the gcode parameter dialog is too short even though the buttons are usable (if you can see them against the background)

The Elitebook is running Ubuntu and its only job is to run the Ox.   I normally generate Gcode on another machine and then transfer though the network, but it woudl be very handy o be able to use the online cam directly at the machine for simple jobs.
![20180918_184215](https://user-images.githubusercontent.com/11569466/45746042-92951380-bc02-11e8-939f-f9a9d22331c6.jpg)

**Comment by openbuilds-engineer** [comment]
![added scrollbar](https://user-images.githubusercontent.com/31449271/45775318-b03c9a00-bc4f-11e8-8919-9e6e8844e09e.gif)

**Comment by openbuilds-engineer** [comment]
Added a Scrollbar - let me know how it goes (:

**Comment by swarfer** [comment]
thanks, will check tonight.
This is an increasing problem with wide screens, they are just not very high in pixel count, usually around 800.
