### ISSUE TITLE
Comments for tool diameter to saved gcode

### ISSUE THREAD

**Issue by tbmartin211** [OpenBuilds/cam#37]
Love what you've done so far - but I generated several gcodes - and was changing tool diameter, etc to get the best cut...now, I don't know which is which.  The "Configure Tool Paths" dialog has the information to create the tool paths - can the toll diameter be added to a comment at the top?

**Comment by openbuilds-engineer** [comment]
Good suggestion, will add it today

**Comment by openbuilds-engineer** [comment]
![endmill dia](https://user-images.githubusercontent.com/31449271/51478037-ed966d00-1d92-11e9-9672-141bcbc82681.PNG)


Done
